---
- name: install unzip
  become: yes
  yum:
    update_cache: yes
    name: unzip
    state: latest

- name: download FITS
  get_url:
    url: "{{ fits_url }}"
    checksum: sha256:{{ fits_256 }}
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    dest: "{{ install_path }}/fits-{{ fits_ver }}.zip"

- name: unpack FITS
  become: yes
  unarchive:
    src: "{{ install_path }}/fits-{{ fits_ver }}.zip"
    dest: /usr/local/lib/
    creates: /usr/local/lib/fits-{{ fits_ver }}/fits.sh
    copy: no

- name: make FITS executable
  become: yes
  file:
    path: /usr/local/lib/fits-{{ fits_ver }}/fits.sh
    mode: 0755

- name: write FITS wrapper
  become: yes
  template:
    src: fits.sh.j2
    dest: /usr/local/bin/{{ item }}
    force: yes
  with_items:
    - fits
    - fits.sh
